### ISSUE TITLE
Idea/Query: Image Clipping!

### ISSUE THREAD

**Issue by HarshArora-1205** [pyncz/tailwind-mask-image#3]
Hey! I tried your plugin and it works similar to normal css, however I wish to create a mask image for a specific div which is part of a section in Next JS Website. In that case, image is clipped from sides and I wish that it should be visible completely.

Code:
```
<div className="relative h-full">
    <div className="relative">
        <p className='md:me-12' onMouseEnter={() => {setIsHovered(true)}} onMouseLeave={() => {setIsHovered(false)}}>
            <span className='text-pr-blue me-2'>Namaste!</span>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Explicabo velit nesciunt quos accusamus iure placeat exercitationem quaerat similique mollitia laborum perferendis beatae natus officia dignissimos aliquid, excepturi sapiente provident laboriosam.
        </p>
   </div>
   <div className="absolute md:me-12 top-0 z-30 mask-[url('../public/Mask.svg')] mask-no-repeat mask-size-[200px] text-pr-black mask-position-center bg-pr-blue">
        <p className="">
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident velit odio voluptatibus consequatur, distinctio similique fuga alias aliquam harum corrupti ducimus iste quisquam praesentium quod in officia fugiat, ratione quas.
        </p>
    </div>
</div>
```

Can you suggest if there is any way around to resolve that?

**Comment by pyncz** [comment]
Hello!
If I understand you correctly, it's an issue with `mask-size-[200px]` class. The section is (probably) smaller than 200px so the image gets cropped. You should use `mask-size-contain` to _inscribe_ the mask image into your section.

**Comment by HarshArora-1205** [comment]
Yes my query is same and I also did `mask-size-contain` but what I actually wish to do is create a mask cursor, which when hovered over a paragraph displayed other text in that region. So for that effect, the svg should be big enough to cover the region. So basically when I move my cursor, the mask moves with that over that paragraph.

`mask-size-contain` limits movement of the mask within that pargraph div. 

I am trying to achieve similar effect: [Youtube](https://www.youtube.com/watch?v=momF_D4odCM)
Here the creator used complete viewport as section and used absolute and relative positions to overlap mask and original content. In my case it is just for a paragraph (part of a section).

**Comment by pyncz** [comment]
Oh. Ok, in this case you used the correct approach setting the fixed mask size (`mask-size-[200px]`).
If the problem was that cursor is not seen outside the section, that's because of the top level `relative`. It doesn't allow your absolute-positioned cursor to get outside it. Remove this class, and everything should be fine.

Check [this CodeSandbox](https://codesandbox.io/p/sandbox/gracious-austin-p826n4?file=%2Fapp/page.tsx%3A12%2C5)

However, if you meant some other kind of clipping, please share reproduction repo / codesandbox.

**Comment by HarshArora-1205** [comment]
Thanks a lot! Really appreciate your help.
